package io.github.mikip98.ssl.automation.modSupport;

import io.github.mikip98.ssl.automation.structures.Color;
import io.github.mikip98.ssl.automation.structures.LightSource;
import io.github.mikip98.ssl.automation.structures.SupportedMod;
import io.github.mikip98.ssl.config.Config;

import java.util.ArrayList;

public class SemiAutomaticSupport {
    // This Class is for mods that have support generated automatically, but with some manual changes.
    // A.K.A. Color and radius tweaks, and some items and blocks may be disabled.

    public static ArrayList<SupportedMod> getSupportedMods() {
        ArrayList<SupportedMod> supportedMods = new ArrayList<>();

        // Mod ID: minecraft
        ArrayList<Color> minecraftColors = new ArrayList<>();
        ArrayList<LightSource> minecraftLightSourceBlocks = new ArrayList<>();
        ArrayList<LightSource> minecraftLightSourceItems = new ArrayList<>();

        minecraftColors.add(new Color("lava_weight_average_color", 213, 94, 20, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("lava", "lava_weight_average_color", 1, "level=0"));
        minecraftLightSourceBlocks.add(new LightSource("lava", "lava_weight_average_color", 2, "level=1"));
        minecraftLightSourceBlocks.add(new LightSource("lava", "lava_weight_average_color", 3, "level=2"));
        minecraftLightSourceBlocks.add(new LightSource("lava", "lava_weight_average_color", 4, "level=3"));
        minecraftLightSourceBlocks.add(new LightSource("lava", "lava_weight_average_color", 5, "level=4"));
        minecraftLightSourceBlocks.add(new LightSource("lava", "lava_weight_average_color", 6, "level=5"));
        minecraftLightSourceBlocks.add(new LightSource("lava", "lava_weight_average_color", 7, "level=6"));
        minecraftLightSourceBlocks.add(new LightSource("lava", "lava_weight_average_color", 8, "level=7"));
        minecraftLightSourceBlocks.add(new LightSource("lava", "lava_weight_average_color", 9, "level=8"));
        minecraftLightSourceBlocks.add(new LightSource("lava", "lava_weight_average_color", 10, "level=9"));
        minecraftLightSourceBlocks.add(new LightSource("lava", "lava_weight_average_color", 11, "level=10"));
        minecraftLightSourceBlocks.add(new LightSource("lava", "lava_weight_average_color", 12, "level=11"));
        minecraftLightSourceBlocks.add(new LightSource("lava", "lava_weight_average_color", 13, "level=12"));
        minecraftLightSourceBlocks.add(new LightSource("lava", "lava_weight_average_color", 14, "level=13"));
        minecraftLightSourceBlocks.add(new LightSource("lava", "lava_weight_average_color", 15, "level=14"));
        minecraftLightSourceBlocks.add(new LightSource("lava", "lava_weight_average_color", 15, "level=15"));
        minecraftColors.add(new Color("brown_mushroom_weight_average_color", 203, 172, 121, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("brown_mushroom", "brown_mushroom_weight_average_color", 1));
        minecraftLightSourceItems.add(new LightSource("brown_mushroom", "brown_mushroom_weight_average_color", 1));
        minecraftColors.add(new Color("torch_weight_average_color", 235, 196, 85, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("torch", "torch_weight_average_color", 14));
        minecraftLightSourceItems.add(new LightSource("torch", "torch_weight_average_color", 14));
        minecraftColors.add(new Color("wall_torch_weight_average_color", 235, 196, 85, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("wall_torch", "wall_torch_weight_average_color", 14));
        minecraftColors.add(new Color("fire_weight_average_color", 222, 165, 81, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("fire", "fire_weight_average_color", 15));
        minecraftColors.add(new Color("soul_fire_weight_average_color", 91, 219, 223, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("soul_fire", "soul_fire_weight_average_color", 10));
        minecraftColors.add(new Color("furnace_weight_average_color", 201, 175, 102, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("furnace", "furnace_weight_average_color", 13, "lit=true"));
        minecraftLightSourceItems.add(new LightSource("furnace", "furnace_weight_average_color", 13));
        minecraftColors.add(new Color("redstone_ore_weight_average_color", 201, 80, 80, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("redstone_ore", "redstone_ore_weight_average_color", 9, "lit=true"));
        minecraftLightSourceItems.add(new LightSource("redstone_ore", "redstone_ore_weight_average_color", 9));
        minecraftColors.add(new Color("deepslate_redstone_ore_weight_average_color", 218, 54, 54, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("deepslate_redstone_ore", "deepslate_redstone_ore_weight_average_color", 9, "lit=true"));
        minecraftLightSourceItems.add(new LightSource("deepslate_redstone_ore", "deepslate_redstone_ore_weight_average_color", 9));
        minecraftColors.add(new Color("redstone_torch_weight_average_color", 245, 85, 36, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("redstone_torch", "redstone_torch_weight_average_color", 7, "lit=true"));
        minecraftLightSourceItems.add(new LightSource("redstone_torch", "redstone_torch_weight_average_color", 7));
        minecraftColors.add(new Color("redstone_wall_torch_weight_average_color", 245, 85, 36, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("redstone_wall_torch", "redstone_wall_torch_weight_average_color", 7, "lit=true"));
        minecraftColors.add(new Color("soul_torch_weight_average_color", 131, 209, 202, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("soul_torch", "soul_torch_weight_average_color", 10));
        minecraftLightSourceItems.add(new LightSource("soul_torch", "soul_torch_weight_average_color", 10));
        minecraftColors.add(new Color("soul_wall_torch_weight_average_color", 131, 209, 202, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("soul_wall_torch", "soul_wall_torch_weight_average_color", 10));
        minecraftColors.add(new Color("glowstone_weight_average_color", 233, 200, 142, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("glowstone", "glowstone_weight_average_color", 15));
        minecraftLightSourceItems.add(new LightSource("glowstone", "glowstone_weight_average_color", 15));
        minecraftColors.add(new Color("nether_portal_weight_average_color", 99, 17, 199, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("nether_portal", "nether_portal_weight_average_color", 11));
        minecraftColors.add(new Color("jack_o_lantern_weight_average_color", 222, 151, 48, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("jack_o_lantern", "jack_o_lantern_weight_average_color", 15));
        minecraftLightSourceItems.add(new LightSource("jack_o_lantern", "jack_o_lantern_weight_average_color", 15));
        minecraftColors.add(new Color("enchanting_table_weight_average_color", 145, 202, 190, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("enchanting_table", "enchanting_table_weight_average_color", 7));
        minecraftLightSourceItems.add(new LightSource("enchanting_table", "enchanting_table_weight_average_color", 7));
        minecraftColors.add(new Color("brewing_stand_weight_average_color", 181, 158, 123, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("brewing_stand", "brewing_stand_weight_average_color", 1));
        minecraftLightSourceItems.add(new LightSource("brewing_stand", "brewing_stand_weight_average_color", 1));
        minecraftColors.add(new Color("lava_cauldron_weight_average_color", 213, 94, 20, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("lava_cauldron", "lava_cauldron_weight_average_color", 15));
        minecraftColors.add(new Color("end_portal_weight_average_color", 52, 36, 75, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("end_portal", "end_portal_weight_average_color", 15));
        minecraftColors.add(new Color("end_portal_frame_weight_average_color", 216, 222, 159, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("end_portal_frame", "end_portal_frame_weight_average_color", 1));
        minecraftLightSourceItems.add(new LightSource("end_portal_frame", "end_portal_frame_weight_average_color", 1));
        minecraftColors.add(new Color("dragon_egg_weight_average_color", 44, 1, 49, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("dragon_egg", "dragon_egg_weight_average_color", 1));
        minecraftLightSourceItems.add(new LightSource("dragon_egg", "dragon_egg_weight_average_color", 1));
        minecraftColors.add(new Color("redstone_lamp_weight_average_color", 232, 176, 111, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("redstone_lamp", "redstone_lamp_weight_average_color", 15, "lit=true"));
        minecraftLightSourceItems.add(new LightSource("redstone_lamp", "redstone_lamp_weight_average_color", 15));
        minecraftColors.add(new Color("ender_chest_weight_average_color", 52, 36, 75, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("ender_chest", "ender_chest_weight_average_color", 7));
        minecraftLightSourceItems.add(new LightSource("ender_chest", "ender_chest_weight_average_color", 7));
        minecraftColors.add(new Color("beacon_weight_average_color", 146, 226, 223, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("beacon", "beacon_weight_average_color", 15));
        minecraftLightSourceItems.add(new LightSource("beacon", "beacon_weight_average_color", 15));
        minecraftColors.add(new Color("light_weight_average_color", 0, 0, 0, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("light", "light_weight_average_color", 1, "level=1"));
        minecraftLightSourceItems.add(new LightSource("light", "light_weight_average_color", 1));
        minecraftLightSourceBlocks.add(new LightSource("light", "light_weight_average_color", 2, "level=2"));
        minecraftLightSourceBlocks.add(new LightSource("light", "light_weight_average_color", 3, "level=3"));
        minecraftLightSourceBlocks.add(new LightSource("light", "light_weight_average_color", 4, "level=4"));
        minecraftLightSourceBlocks.add(new LightSource("light", "light_weight_average_color", 5, "level=5"));
        minecraftLightSourceBlocks.add(new LightSource("light", "light_weight_average_color", 6, "level=6"));
        minecraftLightSourceBlocks.add(new LightSource("light", "light_weight_average_color", 7, "level=7"));
        minecraftLightSourceBlocks.add(new LightSource("light", "light_weight_average_color", 8, "level=8"));
        minecraftLightSourceBlocks.add(new LightSource("light", "light_weight_average_color", 9, "level=9"));
        minecraftLightSourceBlocks.add(new LightSource("light", "light_weight_average_color", 10, "level=10"));
        minecraftLightSourceBlocks.add(new LightSource("light", "light_weight_average_color", 11, "level=11"));
        minecraftLightSourceBlocks.add(new LightSource("light", "light_weight_average_color", 12, "level=12"));
        minecraftLightSourceBlocks.add(new LightSource("light", "light_weight_average_color", 13, "level=13"));
        minecraftLightSourceBlocks.add(new LightSource("light", "light_weight_average_color", 14, "level=14"));
        minecraftLightSourceBlocks.add(new LightSource("light", "light_weight_average_color", 15, "level=15"));
        minecraftColors.add(new Color("sea_lantern_weight_average_color", 204, 222, 213, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("sea_lantern", "sea_lantern_weight_average_color", 15));
        minecraftLightSourceItems.add(new LightSource("sea_lantern", "sea_lantern_weight_average_color", 15));
        minecraftColors.add(new Color("end_rod_weight_average_color", 244, 234, 219, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("end_rod", "end_rod_weight_average_color", 14));
        minecraftLightSourceItems.add(new LightSource("end_rod", "end_rod_weight_average_color", 14));
        minecraftColors.add(new Color("end_gateway_weight_average_color", 52, 36, 75, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("end_gateway", "end_gateway_weight_average_color", 15));
        minecraftColors.add(new Color("magma_block_weight_average_color", 228, 115, 31, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("magma_block", "magma_block_weight_average_color", 3));
        minecraftLightSourceItems.add(new LightSource("magma_block", "magma_block_weight_average_color", 3));
        minecraftColors.add(new Color("sea_pickle_weight_average_color", 162, 193, 139, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("sea_pickle", "sea_pickle_weight_average_color", 6));
        minecraftLightSourceItems.add(new LightSource("sea_pickle", "sea_pickle_weight_average_color", 6));
        minecraftColors.add(new Color("conduit_weight_average_color", 180, 158, 134, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("conduit", "conduit_weight_average_color", 15));
        minecraftLightSourceItems.add(new LightSource("conduit", "conduit_weight_average_color", 15));
        minecraftColors.add(new Color("smoker_weight_average_color", 186, 142, 64, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("smoker", "smoker_weight_average_color", 13, "lit=true"));
        minecraftLightSourceItems.add(new LightSource("smoker", "smoker_weight_average_color", 13));
        minecraftColors.add(new Color("blast_furnace_weight_average_color", 174, 141, 108, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("blast_furnace", "blast_furnace_weight_average_color", 13, "lit=true"));
        minecraftLightSourceItems.add(new LightSource("blast_furnace", "blast_furnace_weight_average_color", 13));
        minecraftColors.add(new Color("lantern_weight_average_color", 227, 176, 100, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("lantern", "lantern_weight_average_color", 15));
        minecraftLightSourceItems.add(new LightSource("lantern", "lantern_weight_average_color", 15));
        minecraftColors.add(new Color("soul_lantern_weight_average_color", 120, 220, 225, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("soul_lantern", "soul_lantern_weight_average_color", 10));
        minecraftLightSourceItems.add(new LightSource("soul_lantern", "soul_lantern_weight_average_color", 10));
        minecraftColors.add(new Color("campfire_weight_average_color", 225, 176, 71, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("campfire", "campfire_weight_average_color", 15, "lit=true"));
        minecraftLightSourceItems.add(new LightSource("campfire", "campfire_weight_average_color", 15));
        minecraftColors.add(new Color("soul_campfire_weight_average_color", 111, 221, 224, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("soul_campfire", "soul_campfire_weight_average_color", 10, "lit=true"));
        minecraftLightSourceItems.add(new LightSource("soul_campfire", "soul_campfire_weight_average_color", 10));
        minecraftColors.add(new Color("shroomlight_weight_average_color", 246, 157, 82, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("shroomlight", "shroomlight_weight_average_color", 15));
        minecraftLightSourceItems.add(new LightSource("shroomlight", "shroomlight_weight_average_color", 15));
        minecraftColors.add(new Color("crying_obsidian_weight_average_color", 107, 7, 191, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("crying_obsidian", "crying_obsidian_weight_average_color", 10));
        minecraftLightSourceItems.add(new LightSource("crying_obsidian", "crying_obsidian_weight_average_color", 10));
        minecraftColors.add(new Color("candle_weight_average_color", 247, 223, 185, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("candle", "candle_weight_average_color", 3, "lit=true"));
        minecraftLightSourceItems.add(new LightSource("candle", "candle_weight_average_color", 3));
        minecraftColors.add(new Color("white_candle_weight_average_color", 234, 230, 212, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("white_candle", "white_candle_weight_average_color", 3, "lit=true"));
        minecraftLightSourceItems.add(new LightSource("white_candle", "white_candle_weight_average_color", 3));
        minecraftColors.add(new Color("orange_candle_weight_average_color", 243, 151, 34, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("orange_candle", "orange_candle_weight_average_color", 3, "lit=true"));
        minecraftLightSourceItems.add(new LightSource("orange_candle", "orange_candle_weight_average_color", 3));
        minecraftColors.add(new Color("magenta_candle_weight_average_color", 217, 103, 180, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("magenta_candle", "magenta_candle_weight_average_color", 3, "lit=true"));
        minecraftLightSourceItems.add(new LightSource("magenta_candle", "magenta_candle_weight_average_color", 3));
        minecraftColors.add(new Color("light_blue_candle_weight_average_color", 86, 180, 213, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("light_blue_candle", "light_blue_candle_weight_average_color", 3, "lit=true"));
        minecraftLightSourceItems.add(new LightSource("light_blue_candle", "light_blue_candle_weight_average_color", 3));
        minecraftColors.add(new Color("yellow_candle_weight_average_color", 236, 206, 92, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("yellow_candle", "yellow_candle_weight_average_color", 3, "lit=true"));
        minecraftLightSourceItems.add(new LightSource("yellow_candle", "yellow_candle_weight_average_color", 3));
        minecraftColors.add(new Color("lime_candle_weight_average_color", 150, 199, 37, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("lime_candle", "lime_candle_weight_average_color", 3, "lit=true"));
        minecraftLightSourceItems.add(new LightSource("lime_candle", "lime_candle_weight_average_color", 3));
        minecraftColors.add(new Color("pink_candle_weight_average_color", 236, 154, 164, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("pink_candle", "pink_candle_weight_average_color", 3, "lit=true"));
        minecraftLightSourceItems.add(new LightSource("pink_candle", "pink_candle_weight_average_color", 3));
        minecraftColors.add(new Color("gray_candle_weight_average_color", 215, 186, 140, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("gray_candle", "gray_candle_weight_average_color", 3, "lit=true"));
        minecraftLightSourceItems.add(new LightSource("gray_candle", "gray_candle_weight_average_color", 3));
        minecraftColors.add(new Color("light_gray_candle_weight_average_color", 230, 211, 161, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("light_gray_candle", "light_gray_candle_weight_average_color", 3, "lit=true"));
        minecraftLightSourceItems.add(new LightSource("light_gray_candle", "light_gray_candle_weight_average_color", 3));
        minecraftColors.add(new Color("cyan_candle_weight_average_color", 84, 194, 164, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("cyan_candle", "cyan_candle_weight_average_color", 3, "lit=true"));
        minecraftLightSourceItems.add(new LightSource("cyan_candle", "cyan_candle_weight_average_color", 3));
        minecraftColors.add(new Color("purple_candle_weight_average_color", 150, 36, 145, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("purple_candle", "purple_candle_weight_average_color", 3, "lit=true"));
        minecraftLightSourceItems.add(new LightSource("purple_candle", "purple_candle_weight_average_color", 3));
        minecraftColors.add(new Color("blue_candle_weight_average_color", 81, 104, 214, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("blue_candle", "blue_candle_weight_average_color", 3, "lit=true"));
        minecraftLightSourceItems.add(new LightSource("blue_candle", "blue_candle_weight_average_color", 3));
        minecraftColors.add(new Color("brown_candle_weight_average_color", 231, 160, 82, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("brown_candle", "brown_candle_weight_average_color", 3, "lit=true"));
        minecraftLightSourceItems.add(new LightSource("brown_candle", "brown_candle_weight_average_color", 3));
        minecraftColors.add(new Color("green_candle_weight_average_color", 174, 165, 25, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("green_candle", "green_candle_weight_average_color", 3, "lit=true"));
        minecraftLightSourceItems.add(new LightSource("green_candle", "green_candle_weight_average_color", 3));
        minecraftColors.add(new Color("red_candle_weight_average_color", 227, 106, 65, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("red_candle", "red_candle_weight_average_color", 3, "lit=true"));
        minecraftLightSourceItems.add(new LightSource("red_candle", "red_candle_weight_average_color", 3));
        minecraftColors.add(new Color("black_candle_weight_average_color", 210, 97, 39, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("black_candle", "black_candle_weight_average_color", 3, "lit=true"));
        minecraftLightSourceItems.add(new LightSource("black_candle", "black_candle_weight_average_color", 3));
        minecraftColors.add(new Color("candle_cake_weight_average_color", 240, 217, 201, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("candle_cake", "candle_cake_weight_average_color", 3, "lit=true"));
        minecraftColors.add(new Color("white_candle_cake_weight_average_color", 239, 217, 203, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("white_candle_cake", "white_candle_cake_weight_average_color", 3, "lit=true"));
        minecraftColors.add(new Color("orange_candle_cake_weight_average_color", 240, 212, 191, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("orange_candle_cake", "orange_candle_cake_weight_average_color", 3, "lit=true"));
        minecraftColors.add(new Color("magenta_candle_cake_weight_average_color", 239, 212, 202, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("magenta_candle_cake", "magenta_candle_cake_weight_average_color", 3, "lit=true"));
        minecraftColors.add(new Color("light_blue_candle_cake_weight_average_color", 233, 215, 203, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("light_blue_candle_cake", "light_blue_candle_cake_weight_average_color", 3, "lit=true"));
        minecraftColors.add(new Color("yellow_candle_cake_weight_average_color", 239, 216, 196, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("yellow_candle_cake", "yellow_candle_cake_weight_average_color", 3, "lit=true"));
        minecraftColors.add(new Color("lime_candle_cake_weight_average_color", 237, 216, 197, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("lime_candle_cake", "lime_candle_cake_weight_average_color", 3, "lit=true"));
        minecraftColors.add(new Color("pink_candle_cake_weight_average_color", 239, 213, 200, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("pink_candle_cake", "pink_candle_cake_weight_average_color", 3, "lit=true"));
        minecraftColors.add(new Color("gray_candle_cake_weight_average_color", 239, 216, 201, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("gray_candle_cake", "gray_candle_cake_weight_average_color", 3, "lit=true"));
        minecraftColors.add(new Color("light_gray_candle_cake_weight_average_color", 239, 216, 201, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("light_gray_candle_cake", "light_gray_candle_cake_weight_average_color", 3, "lit=true"));
        minecraftColors.add(new Color("cyan_candle_cake_weight_average_color", 237, 216, 202, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("cyan_candle_cake", "cyan_candle_cake_weight_average_color", 3, "lit=true"));
        minecraftColors.add(new Color("purple_candle_cake_weight_average_color", 238, 213, 201, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("purple_candle_cake", "purple_candle_cake_weight_average_color", 3, "lit=true"));
        minecraftColors.add(new Color("blue_candle_cake_weight_average_color", 235, 213, 203, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("blue_candle_cake", "blue_candle_cake_weight_average_color", 3, "lit=true"));
        minecraftColors.add(new Color("brown_candle_cake_weight_average_color", 239, 215, 200, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("brown_candle_cake", "brown_candle_cake_weight_average_color", 3, "lit=true"));
        minecraftColors.add(new Color("green_candle_cake_weight_average_color", 239, 216, 201, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("green_candle_cake", "green_candle_cake_weight_average_color", 3, "lit=true"));
        minecraftColors.add(new Color("red_candle_cake_weight_average_color", 239, 213, 198, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("red_candle_cake", "red_candle_cake_weight_average_color", 3, "lit=true"));
        minecraftColors.add(new Color("black_candle_cake_weight_average_color", 239, 215, 201, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("black_candle_cake", "black_candle_cake_weight_average_color", 3, "lit=true"));
        minecraftColors.add(new Color("amethyst_cluster_weight_average_color", 192, 151, 223, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("amethyst_cluster", "amethyst_cluster_weight_average_color", 5));
        minecraftLightSourceItems.add(new LightSource("amethyst_cluster", "amethyst_cluster_weight_average_color", 5));
        minecraftColors.add(new Color("large_amethyst_bud_weight_average_color", 193, 156, 220, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("large_amethyst_bud", "large_amethyst_bud_weight_average_color", 4));
        minecraftLightSourceItems.add(new LightSource("large_amethyst_bud", "large_amethyst_bud_weight_average_color", 4));
        minecraftColors.add(new Color("medium_amethyst_bud_weight_average_color", 192, 149, 222, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("medium_amethyst_bud", "medium_amethyst_bud_weight_average_color", 2));
        minecraftLightSourceItems.add(new LightSource("medium_amethyst_bud", "medium_amethyst_bud_weight_average_color", 2));
        minecraftColors.add(new Color("small_amethyst_bud_weight_average_color", 151, 116, 213, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("small_amethyst_bud", "small_amethyst_bud_weight_average_color", 1));
        minecraftLightSourceItems.add(new LightSource("small_amethyst_bud", "small_amethyst_bud_weight_average_color", 1));
        minecraftColors.add(new Color("sculk_sensor_weight_average_color", 26, 178, 188, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("sculk_sensor", "sculk_sensor_weight_average_color", 1));
        minecraftLightSourceItems.add(new LightSource("sculk_sensor", "sculk_sensor_weight_average_color", 1));
        minecraftColors.add(new Color("calibrated_sculk_sensor_weight_average_color", 26, 178, 188, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("calibrated_sculk_sensor", "calibrated_sculk_sensor_weight_average_color", 1));
        minecraftLightSourceItems.add(new LightSource("calibrated_sculk_sensor", "calibrated_sculk_sensor_weight_average_color", 1));
        minecraftColors.add(new Color("sculk_catalyst_weight_average_color", 112, 187, 172, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("sculk_catalyst", "sculk_catalyst_weight_average_color", 6));
        minecraftLightSourceItems.add(new LightSource("sculk_catalyst", "sculk_catalyst_weight_average_color", 6));
        minecraftColors.add(new Color("ochre_froglight_weight_average_color", 249, 242, 198, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("ochre_froglight", "ochre_froglight_weight_average_color", 15));
        minecraftLightSourceItems.add(new LightSource("ochre_froglight", "ochre_froglight_weight_average_color", 15));
        minecraftColors.add(new Color("verdant_froglight_weight_average_color", 228, 244, 227, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("verdant_froglight", "verdant_froglight_weight_average_color", 15));
        minecraftLightSourceItems.add(new LightSource("verdant_froglight", "verdant_froglight_weight_average_color", 15));
        minecraftColors.add(new Color("pearlescent_froglight_weight_average_color", 245, 239, 239, Config.auto_alpha));
        minecraftLightSourceBlocks.add(new LightSource("pearlescent_froglight", "pearlescent_froglight_weight_average_color", 15));
        minecraftLightSourceItems.add(new LightSource("pearlescent_froglight", "pearlescent_froglight_weight_average_color", 15));
        supportedMods.add(new SupportedMod("minecraft", "minecraft", "jar", minecraftColors, minecraftLightSourceBlocks, minecraftLightSourceItems));

        // Mod ID: betternether
        ArrayList<Color> betternetherColors = new ArrayList<>();
        ArrayList<LightSource> betternetherLightSourceBlocks = new ArrayList<>();
        ArrayList<LightSource> betternetherLightSourceItems = new ArrayList<>();

        betternetherColors.add(new Color("willow_torch_weight_average_color", 190, 212, 233, Config.auto_alpha));
        betternetherLightSourceBlocks.add(new LightSource("willow_torch", "willow_torch_weight_average_color", 15));
        betternetherLightSourceItems.add(new LightSource("willow_torch", "willow_torch_weight_average_color", 15));
        betternetherColors.add(new Color("cincinnasite_lantern_weight_average_color", 246, 170, 55, Config.auto_alpha));
        betternetherLightSourceBlocks.add(new LightSource("cincinnasite_lantern", "cincinnasite_lantern_weight_average_color", 15));
        betternetherLightSourceItems.add(new LightSource("cincinnasite_lantern", "cincinnasite_lantern_weight_average_color", 15));
        betternetherColors.add(new Color("cincinnasite_lantern_small_weight_average_color", 236, 162, 45, Config.auto_alpha));
        betternetherLightSourceBlocks.add(new LightSource("cincinnasite_lantern_small", "cincinnasite_lantern_small_weight_average_color", 15));
        betternetherLightSourceItems.add(new LightSource("cincinnasite_lantern_small", "cincinnasite_lantern_small_weight_average_color", 15));
        betternetherColors.add(new Color("nether_redstone_ore_weight_average_color", 197, 61, 48, Config.auto_alpha));
        betternetherLightSourceBlocks.add(new LightSource("nether_redstone_ore", "nether_redstone_ore_weight_average_color", 9, "lit=true"));
        betternetherColors.add(new Color("blue_weeping_obsidian_weight_average_color", 27, 111, 228, Config.auto_alpha));
        betternetherLightSourceBlocks.add(new LightSource("blue_weeping_obsidian", "blue_weeping_obsidian_weight_average_color", 14));
        betternetherColors.add(new Color("weeping_obsidian_weight_average_color", 141, 16, 231, Config.auto_alpha));
        betternetherLightSourceBlocks.add(new LightSource("weeping_obsidian", "weeping_obsidian_weight_average_color", 14));
        betternetherColors.add(new Color("blue_crying_obsidian_weight_average_color", 19, 87, 194, Config.auto_alpha));
        betternetherLightSourceBlocks.add(new LightSource("blue_crying_obsidian", "blue_crying_obsidian_weight_average_color", 10));
        betternetherColors.add(new Color("lucis_spore_weight_average_color", 216, 208, 96, Config.auto_alpha));
        betternetherLightSourceBlocks.add(new LightSource("lucis_spore", "lucis_spore_weight_average_color", 7));
        betternetherLightSourceItems.add(new LightSource("lucis_spore", "lucis_spore_weight_average_color", 7));
        betternetherColors.add(new Color("giant_lucis_weight_average_color", 247, 176, 49, Config.auto_alpha));
        betternetherLightSourceBlocks.add(new LightSource("giant_lucis", "giant_lucis_weight_average_color", 15));
        betternetherLightSourceItems.add(new LightSource("giant_lucis", "giant_lucis_weight_average_color", 15));
        betternetherColors.add(new Color("giant_mold_sapling_weight_average_color", 206, 180, 167, Config.auto_alpha));
        betternetherLightSourceBlocks.add(new LightSource("giant_mold_sapling", "giant_mold_sapling_weight_average_color", 7));
        betternetherLightSourceItems.add(new LightSource("giant_mold_sapling", "giant_mold_sapling_weight_average_color", 7));
        betternetherColors.add(new Color("jellyfish_mushroom_sapling_weight_average_color", 182, 149, 246, Config.auto_alpha));
        betternetherLightSourceBlocks.add(new LightSource("jellyfish_mushroom_sapling", "jellyfish_mushroom_sapling_weight_average_color", 9));
        betternetherLightSourceItems.add(new LightSource("jellyfish_mushroom_sapling", "jellyfish_mushroom_sapling_weight_average_color", 9));
        betternetherColors.add(new Color("eye_seed_weight_average_color", 191, 160, 159, Config.auto_alpha));
        betternetherLightSourceBlocks.add(new LightSource("eye_seed", "eye_seed_weight_average_color", 9));
        betternetherLightSourceItems.add(new LightSource("eye_seed", "eye_seed_weight_average_color", 9));
        betternetherColors.add(new Color("golden_vine_weight_average_color", 242, 196, 48, Config.auto_alpha));
        betternetherLightSourceBlocks.add(new LightSource("golden_vine", "golden_vine_weight_average_color", 15));
        betternetherLightSourceItems.add(new LightSource("golden_vine", "golden_vine_weight_average_color", 15));
        betternetherColors.add(new Color("ink_bush_seed_weight_average_color", 119, 63, 45, Config.auto_alpha));
        betternetherLightSourceBlocks.add(new LightSource("ink_bush_seed", "ink_bush_seed_weight_average_color", 9));
        betternetherLightSourceItems.add(new LightSource("ink_bush_seed", "ink_bush_seed_weight_average_color", 9));
        betternetherColors.add(new Color("black_apple_seed_weight_average_color", 220, 144, 21, Config.auto_alpha));
        betternetherLightSourceBlocks.add(new LightSource("black_apple_seed", "black_apple_seed_weight_average_color", 9));
        betternetherLightSourceItems.add(new LightSource("black_apple_seed", "black_apple_seed_weight_average_color", 9));
        betternetherColors.add(new Color("neon_equisetum_weight_average_color", 142, 111, 225, Config.auto_alpha));
        betternetherLightSourceBlocks.add(new LightSource("neon_equisetum", "neon_equisetum_weight_average_color", 15));
        betternetherLightSourceItems.add(new LightSource("neon_equisetum", "neon_equisetum_weight_average_color", 15));
        betternetherColors.add(new Color("hook_mushroom_weight_average_color", 223, 132, 183, Config.auto_alpha));
        betternetherLightSourceBlocks.add(new LightSource("hook_mushroom", "hook_mushroom_weight_average_color", 13));
        betternetherLightSourceItems.add(new LightSource("hook_mushroom", "hook_mushroom_weight_average_color", 13));
        betternetherColors.add(new Color("whispering_gourd_lantern_weight_average_color", 124, 109, 212, Config.auto_alpha));
        betternetherLightSourceBlocks.add(new LightSource("whispering_gourd_lantern", "whispering_gourd_lantern_weight_average_color", 15));
        betternetherLightSourceItems.add(new LightSource("whispering_gourd_lantern", "whispering_gourd_lantern_weight_average_color", 15));
        betternetherColors.add(new Color("pig_statue_respawner_weight_average_color", 219, 154, 63, Config.auto_alpha));
        betternetherLightSourceBlocks.add(new LightSource("pig_statue_respawner", "pig_statue_respawner_weight_average_color", 15));
        betternetherLightSourceItems.add(new LightSource("pig_statue_respawner", "pig_statue_respawner_weight_average_color", 15));
        betternetherColors.add(new Color("geyser_weight_average_color", 225, 113, 32, Config.auto_alpha));
        betternetherLightSourceBlocks.add(new LightSource("geyser", "geyser_weight_average_color", 10));
        betternetherLightSourceItems.add(new LightSource("geyser", "geyser_weight_average_color", 10));
        betternetherColors.add(new Color("glowstone_stalactite_weight_average_color", 233, 200, 142, Config.auto_alpha));
        betternetherLightSourceBlocks.add(new LightSource("glowstone_stalactite", "glowstone_stalactite_weight_average_color", 15));
        betternetherLightSourceItems.add(new LightSource("glowstone_stalactite", "glowstone_stalactite_weight_average_color", 15));
        betternetherColors.add(new Color("blackstone_furnace_weight_average_color", 238, 125, 15, Config.auto_alpha));
        betternetherLightSourceBlocks.add(new LightSource("blackstone_furnace", "blackstone_furnace_weight_average_color", 13, "lit=true"));
        betternetherLightSourceItems.add(new LightSource("blackstone_furnace", "blackstone_furnace_weight_average_color", 13));
        betternetherColors.add(new Color("basalt_furnace_weight_average_color", 230, 125, 21, Config.auto_alpha));
        betternetherLightSourceBlocks.add(new LightSource("basalt_furnace", "basalt_furnace_weight_average_color", 13, "lit=true"));
        betternetherLightSourceItems.add(new LightSource("basalt_furnace", "basalt_furnace_weight_average_color", 13));
        betternetherColors.add(new Color("netherrack_furnace_weight_average_color", 226, 118, 20, Config.auto_alpha));
        betternetherLightSourceBlocks.add(new LightSource("netherrack_furnace", "netherrack_furnace_weight_average_color", 13, "lit=true"));
        betternetherLightSourceItems.add(new LightSource("netherrack_furnace", "netherrack_furnace_weight_average_color", 13));
        betternetherColors.add(new Color("cincinnasite_forge_weight_average_color", 235, 136, 36, Config.auto_alpha));
        betternetherLightSourceBlocks.add(new LightSource("cincinnasite_forge", "cincinnasite_forge_weight_average_color", 13, "lit=true"));
        betternetherLightSourceItems.add(new LightSource("cincinnasite_forge", "cincinnasite_forge_weight_average_color", 13));
        betternetherColors.add(new Color("nether_brewing_stand_weight_average_color", 228, 155, 52, Config.auto_alpha));
        betternetherLightSourceBlocks.add(new LightSource("nether_brewing_stand", "nether_brewing_stand_weight_average_color", 1));
        betternetherLightSourceItems.add(new LightSource("nether_brewing_stand", "nether_brewing_stand_weight_average_color", 1));
        betternetherColors.add(new Color("rubeus_cone_weight_average_color", 72, 153, 214, Config.auto_alpha));
        betternetherLightSourceBlocks.add(new LightSource("rubeus_cone", "rubeus_cone_weight_average_color", 15));
        betternetherLightSourceItems.add(new LightSource("rubeus_cone", "rubeus_cone_weight_average_color", 15));
        betternetherColors.add(new Color("nether_sakura_leaves_weight_average_color", 216, 104, 136, Config.auto_alpha));
        betternetherLightSourceBlocks.add(new LightSource("nether_sakura_leaves", "nether_sakura_leaves_weight_average_color", 13));
        betternetherLightSourceItems.add(new LightSource("nether_sakura_leaves", "nether_sakura_leaves_weight_average_color", 13));
        betternetherColors.add(new Color("soul_lily_sapling_weight_average_color", 211, 117, 46, Config.auto_alpha));
        betternetherLightSourceBlocks.add(new LightSource("soul_lily_sapling", "soul_lily_sapling_weight_average_color", 9));
        betternetherLightSourceItems.add(new LightSource("soul_lily_sapling", "soul_lily_sapling_weight_average_color", 9));
        betternetherColors.add(new Color("lucis_mushroom_weight_average_color", 226, 214, 107, Config.auto_alpha));
        betternetherLightSourceBlocks.add(new LightSource("lucis_mushroom", "lucis_mushroom_weight_average_color", 15));
        betternetherColors.add(new Color("jellyfish_mushroom_weight_average_color", 173, 192, 195, Config.auto_alpha));
        betternetherLightSourceBlocks.add(new LightSource("jellyfish_mushroom", "jellyfish_mushroom_weight_average_color", 13));
        betternetherColors.add(new Color("eyeball_weight_average_color", 200, 177, 177, Config.auto_alpha));
        betternetherLightSourceBlocks.add(new LightSource("eyeball", "eyeball_weight_average_color", 15));
        betternetherLightSourceItems.add(new LightSource("eyeball", "eyeball_weight_average_color", 15));
        betternetherColors.add(new Color("eyeball_small_weight_average_color", 193, 164, 164, Config.auto_alpha));
        betternetherLightSourceBlocks.add(new LightSource("eyeball_small", "eyeball_small_weight_average_color", 15));
        betternetherLightSourceItems.add(new LightSource("eyeball_small", "eyeball_small_weight_average_color", 15));
        betternetherColors.add(new Color("lumabus_seed_weight_average_color", 61, 221, 202, Config.auto_alpha));
        betternetherLightSourceBlocks.add(new LightSource("lumabus_seed", "lumabus_seed_weight_average_color", 9));
        betternetherLightSourceItems.add(new LightSource("lumabus_seed", "lumabus_seed_weight_average_color", 9));
        betternetherColors.add(new Color("golden_lumabus_seed_weight_average_color", 86, 220, 148, Config.auto_alpha));
        betternetherLightSourceBlocks.add(new LightSource("golden_lumabus_seed", "golden_lumabus_seed_weight_average_color", 9));
        betternetherLightSourceItems.add(new LightSource("golden_lumabus_seed", "golden_lumabus_seed_weight_average_color", 9));
        supportedMods.add(new SupportedMod("betternether", "betternether", "better-nether", betternetherColors, betternetherLightSourceBlocks, betternetherLightSourceItems));

        // Mod ID: betterend
        ArrayList<Color> betterendColors = new ArrayList<>();
        ArrayList<LightSource> betterendLightSourceBlocks = new ArrayList<>();
        ArrayList<LightSource> betterendLightSourceItems = new ArrayList<>();

        betterendColors.add(new Color("flavolite_lantern_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("flavolite_lantern", "flavolite_lantern_weight_average_color", 15));
        betterendColors.add(new Color("flavolite_furnace_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("flavolite_furnace", "flavolite_furnace_weight_average_color", 13, "lit=true"));
        betterendColors.add(new Color("violecite_lantern_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("violecite_lantern", "violecite_lantern_weight_average_color", 15));
        betterendColors.add(new Color("violecite_furnace_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("violecite_furnace", "violecite_furnace_weight_average_color", 13, "lit=true"));
        betterendColors.add(new Color("sulphuric_rock_lantern_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("sulphuric_rock_lantern", "sulphuric_rock_lantern_weight_average_color", 15));
        betterendColors.add(new Color("sulphuric_rock_furnace_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("sulphuric_rock_furnace", "sulphuric_rock_furnace_weight_average_color", 13, "lit=true"));
        betterendColors.add(new Color("virid_jadestone_lantern_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("virid_jadestone_lantern", "virid_jadestone_lantern_weight_average_color", 15));
        betterendColors.add(new Color("virid_jadestone_furnace_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("virid_jadestone_furnace", "virid_jadestone_furnace_weight_average_color", 13, "lit=true"));
        betterendColors.add(new Color("azure_jadestone_lantern_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("azure_jadestone_lantern", "azure_jadestone_lantern_weight_average_color", 15));
        betterendColors.add(new Color("azure_jadestone_furnace_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("azure_jadestone_furnace", "azure_jadestone_furnace_weight_average_color", 13, "lit=true"));
        betterendColors.add(new Color("sandy_jadestone_lantern_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("sandy_jadestone_lantern", "sandy_jadestone_lantern_weight_average_color", 15));
        betterendColors.add(new Color("sandy_jadestone_furnace_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("sandy_jadestone_furnace", "sandy_jadestone_furnace_weight_average_color", 13, "lit=true"));
        betterendColors.add(new Color("umbralith_lantern_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("umbralith_lantern", "umbralith_lantern_weight_average_color", 15));
        betterendColors.add(new Color("umbralith_furnace_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("umbralith_furnace", "umbralith_furnace_weight_average_color", 13, "lit=true"));
        betterendColors.add(new Color("mossy_glowshroom_sapling_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("mossy_glowshroom_sapling", "mossy_glowshroom_sapling_weight_average_color", 7));
        betterendColors.add(new Color("mossy_glowshroom_hymenophore_weight_average_color", 80, 183, 255, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("mossy_glowshroom_hymenophore", "mossy_glowshroom_hymenophore_weight_average_color", 15));
        betterendLightSourceItems.add(new LightSource("mossy_glowshroom_hymenophore", "mossy_glowshroom_hymenophore_weight_average_color", 15));
        betterendColors.add(new Color("mossy_glowshroom_fur_weight_average_color", 98, 204, 255, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("mossy_glowshroom_fur", "mossy_glowshroom_fur_weight_average_color", 15));
        betterendLightSourceItems.add(new LightSource("mossy_glowshroom_fur", "mossy_glowshroom_fur_weight_average_color", 15));
        betterendColors.add(new Color("end_lotus_flower_weight_average_color", 218, 162, 226, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("end_lotus_flower", "end_lotus_flower_weight_average_color", 15));
        betterendColors.add(new Color("tenanea_flowers_weight_average_color", 221, 218, 213, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("tenanea_flowers", "tenanea_flowers_weight_average_color", 15));
        betterendLightSourceItems.add(new LightSource("tenanea_flowers", "tenanea_flowers_weight_average_color", 15));
        betterendColors.add(new Color("umbrella_tree_cluster_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("umbrella_tree_cluster", "umbrella_tree_cluster_weight_average_color", 15));
        betterendColors.add(new Color("umbrella_moss_weight_average_color", 196, 147, 90, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("umbrella_moss", "umbrella_moss_weight_average_color", 11));
        betterendLightSourceItems.add(new LightSource("umbrella_moss", "umbrella_moss_weight_average_color", 11));
        betterendColors.add(new Color("creeping_moss_weight_average_color", 71, 170, 219, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("creeping_moss", "creeping_moss_weight_average_color", 11));
        betterendLightSourceItems.add(new LightSource("creeping_moss", "creeping_moss_weight_average_color", 11));
        betterendColors.add(new Color("twisted_umbrella_moss_weight_average_color", 123, 92, 173, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("twisted_umbrella_moss", "twisted_umbrella_moss_weight_average_color", 12));
        betterendLightSourceItems.add(new LightSource("twisted_umbrella_moss", "twisted_umbrella_moss_weight_average_color", 12));
        betterendColors.add(new Color("flammalix_weight_average_color", 249, 94, 28, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("flammalix", "flammalix_weight_average_color", 12));
        betterendColors.add(new Color("blue_vine_lantern_weight_average_color", 122, 224, 252, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("blue_vine_lantern", "blue_vine_lantern_weight_average_color", 15));
        betterendLightSourceItems.add(new LightSource("blue_vine_lantern", "blue_vine_lantern_weight_average_color", 15));
        betterendColors.add(new Color("blue_vine_fur_weight_average_color", 78, 205, 250, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("blue_vine_fur", "blue_vine_fur_weight_average_color", 15));
        betterendLightSourceItems.add(new LightSource("blue_vine_fur", "blue_vine_fur_weight_average_color", 15));
        betterendColors.add(new Color("glowing_pillar_seed_weight_average_color", 253, 155, 57, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("glowing_pillar_seed", "glowing_pillar_seed_weight_average_color", 3));
        betterendLightSourceItems.add(new LightSource("glowing_pillar_seed", "glowing_pillar_seed_weight_average_color", 3));
        betterendColors.add(new Color("glowing_pillar_luminophor_weight_average_color", 255, 157, 56, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("glowing_pillar_luminophor", "glowing_pillar_luminophor_weight_average_color", 15));
        betterendLightSourceItems.add(new LightSource("glowing_pillar_luminophor", "glowing_pillar_luminophor_weight_average_color", 15));
        betterendColors.add(new Color("glowing_pillar_leaves_weight_average_color", 253, 148, 67, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("glowing_pillar_leaves", "glowing_pillar_leaves_weight_average_color", 15));
        betterendLightSourceItems.add(new LightSource("glowing_pillar_leaves", "glowing_pillar_leaves_weight_average_color", 15));
        betterendColors.add(new Color("bolux_mushroom_weight_average_color", 176, 161, 165, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("bolux_mushroom", "bolux_mushroom_weight_average_color", 10));
        betterendLightSourceItems.add(new LightSource("bolux_mushroom", "bolux_mushroom_weight_average_color", 10));
        betterendColors.add(new Color("lumecorn_weight_average_color", 131, 212, 222, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("lumecorn", "lumecorn_weight_average_color", 15));
        betterendColors.add(new Color("large_amaranita_mushroom_weight_average_color", 181, 127, 117, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("large_amaranita_mushroom", "large_amaranita_mushroom_weight_average_color", 15));
        betterendColors.add(new Color("amaranita_lantern_weight_average_color", 152, 218, 198, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("amaranita_lantern", "amaranita_lantern_weight_average_color", 15));
        betterendLightSourceItems.add(new LightSource("amaranita_lantern", "amaranita_lantern_weight_average_color", 15));
        betterendColors.add(new Color("amaranita_fur_weight_average_color", 178, 232, 214, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("amaranita_fur", "amaranita_fur_weight_average_color", 15));
        betterendLightSourceItems.add(new LightSource("amaranita_fur", "amaranita_fur_weight_average_color", 15));
        betterendColors.add(new Color("neon_cactus_weight_average_color", 146, 196, 190, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("neon_cactus", "neon_cactus_weight_average_color", 15));
        betterendLightSourceItems.add(new LightSource("neon_cactus", "neon_cactus_weight_average_color", 15));
        betterendColors.add(new Color("neon_cactus_block_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("neon_cactus_block", "neon_cactus_block_weight_average_color", 15));
        betterendColors.add(new Color("neon_cactus_stairs_weight_average_color", 121, 178, 202, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("neon_cactus_stairs", "neon_cactus_stairs_weight_average_color", 15));
        betterendLightSourceItems.add(new LightSource("neon_cactus_stairs", "neon_cactus_stairs_weight_average_color", 15));
        betterendColors.add(new Color("neon_cactus_slab_weight_average_color", 121, 178, 202, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("neon_cactus_slab", "neon_cactus_slab_weight_average_color", 15));
        betterendLightSourceItems.add(new LightSource("neon_cactus_slab", "neon_cactus_slab_weight_average_color", 15));
        betterendColors.add(new Color("cave_pumpkin_weight_average_color", 207, 152, 137, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("cave_pumpkin", "cave_pumpkin_weight_average_color", 15));
        betterendLightSourceItems.add(new LightSource("cave_pumpkin", "cave_pumpkin_weight_average_color", 15));
        betterendColors.add(new Color("end_lily_weight_average_color", 116, 156, 218, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("end_lily", "end_lily_weight_average_color", 13));
        betterendColors.add(new Color("hydralux_weight_average_color", 177, 172, 141, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("hydralux", "hydralux_weight_average_color", 15));
        betterendColors.add(new Color("pond_anemone_weight_average_color", 219, 179, 158, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("pond_anemone", "pond_anemone_weight_average_color", 13));
        betterendLightSourceItems.add(new LightSource("pond_anemone", "pond_anemone_weight_average_color", 13));
        betterendColors.add(new Color("purple_polypore_weight_average_color", 188, 119, 216, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("purple_polypore", "purple_polypore_weight_average_color", 13));
        betterendLightSourceItems.add(new LightSource("purple_polypore", "purple_polypore_weight_average_color", 13));
        betterendColors.add(new Color("aurant_polypore_weight_average_color", 141, 167, 202, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("aurant_polypore", "aurant_polypore_weight_average_color", 13));
        betterendLightSourceItems.add(new LightSource("aurant_polypore", "aurant_polypore_weight_average_color", 13));
        betterendColors.add(new Color("bulb_moss_weight_average_color", 194, 120, 31, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("bulb_moss", "bulb_moss_weight_average_color", 12));
        betterendLightSourceItems.add(new LightSource("bulb_moss", "bulb_moss_weight_average_color", 12));
        betterendColors.add(new Color("dense_vine_weight_average_color", 113, 202, 210, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("dense_vine", "dense_vine_weight_average_color", 15));
        betterendLightSourceItems.add(new LightSource("dense_vine", "dense_vine_weight_average_color", 15));
        betterendColors.add(new Color("bulb_vine_weight_average_color", 214, 170, 202, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("bulb_vine", "bulb_vine_weight_average_color", 15));
        betterendLightSourceItems.add(new LightSource("bulb_vine", "bulb_vine_weight_average_color", 15));
        betterendColors.add(new Color("filalux_weight_average_color", 169, 156, 169, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("filalux", "filalux_weight_average_color", 15));
        betterendLightSourceItems.add(new LightSource("filalux", "filalux_weight_average_color", 15));
        betterendColors.add(new Color("filalux_lantern_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("filalux_lantern", "filalux_lantern_weight_average_color", 15));
        betterendColors.add(new Color("thallasium_chandelier_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("thallasium_chandelier", "thallasium_chandelier_weight_average_color", 15));
        betterendColors.add(new Color("thallasium_bulb_lantern_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("thallasium_bulb_lantern", "thallasium_bulb_lantern_weight_average_color", 15));
        betterendColors.add(new Color("thallasium_bulb_lantern_white_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("thallasium_bulb_lantern_white", "thallasium_bulb_lantern_white_weight_average_color", 15));
        betterendColors.add(new Color("thallasium_bulb_lantern_gray_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("thallasium_bulb_lantern_gray", "thallasium_bulb_lantern_gray_weight_average_color", 15));
        betterendColors.add(new Color("thallasium_bulb_lantern_light_gray_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("thallasium_bulb_lantern_light_gray", "thallasium_bulb_lantern_light_gray_weight_average_color", 15));
        betterendColors.add(new Color("thallasium_bulb_lantern_black_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("thallasium_bulb_lantern_black", "thallasium_bulb_lantern_black_weight_average_color", 15));
        betterendColors.add(new Color("thallasium_bulb_lantern_blue_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("thallasium_bulb_lantern_blue", "thallasium_bulb_lantern_blue_weight_average_color", 15));
        betterendColors.add(new Color("thallasium_bulb_lantern_lime_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("thallasium_bulb_lantern_lime", "thallasium_bulb_lantern_lime_weight_average_color", 15));
        betterendColors.add(new Color("thallasium_bulb_lantern_magenta_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("thallasium_bulb_lantern_magenta", "thallasium_bulb_lantern_magenta_weight_average_color", 15));
        betterendColors.add(new Color("thallasium_bulb_lantern_red_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("thallasium_bulb_lantern_red", "thallasium_bulb_lantern_red_weight_average_color", 15));
        betterendColors.add(new Color("thallasium_bulb_lantern_orange_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("thallasium_bulb_lantern_orange", "thallasium_bulb_lantern_orange_weight_average_color", 15));
        betterendColors.add(new Color("thallasium_bulb_lantern_purple_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("thallasium_bulb_lantern_purple", "thallasium_bulb_lantern_purple_weight_average_color", 15));
        betterendColors.add(new Color("thallasium_bulb_lantern_cyan_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("thallasium_bulb_lantern_cyan", "thallasium_bulb_lantern_cyan_weight_average_color", 15));
        betterendColors.add(new Color("thallasium_bulb_lantern_brown_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("thallasium_bulb_lantern_brown", "thallasium_bulb_lantern_brown_weight_average_color", 15));
        betterendColors.add(new Color("thallasium_bulb_lantern_green_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("thallasium_bulb_lantern_green", "thallasium_bulb_lantern_green_weight_average_color", 15));
        betterendColors.add(new Color("thallasium_bulb_lantern_yellow_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("thallasium_bulb_lantern_yellow", "thallasium_bulb_lantern_yellow_weight_average_color", 15));
        betterendColors.add(new Color("thallasium_bulb_lantern_pink_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("thallasium_bulb_lantern_pink", "thallasium_bulb_lantern_pink_weight_average_color", 15));
        betterendColors.add(new Color("thallasium_bulb_lantern_light_blue_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("thallasium_bulb_lantern_light_blue", "thallasium_bulb_lantern_light_blue_weight_average_color", 15));
        betterendColors.add(new Color("terminite_chandelier_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("terminite_chandelier", "terminite_chandelier_weight_average_color", 15));
        betterendColors.add(new Color("terminite_bulb_lantern_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("terminite_bulb_lantern", "terminite_bulb_lantern_weight_average_color", 15));
        betterendColors.add(new Color("terminite_bulb_lantern_white_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("terminite_bulb_lantern_white", "terminite_bulb_lantern_white_weight_average_color", 15));
        betterendColors.add(new Color("terminite_bulb_lantern_gray_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("terminite_bulb_lantern_gray", "terminite_bulb_lantern_gray_weight_average_color", 15));
        betterendColors.add(new Color("terminite_bulb_lantern_light_gray_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("terminite_bulb_lantern_light_gray", "terminite_bulb_lantern_light_gray_weight_average_color", 15));
        betterendColors.add(new Color("terminite_bulb_lantern_black_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("terminite_bulb_lantern_black", "terminite_bulb_lantern_black_weight_average_color", 15));
        betterendColors.add(new Color("terminite_bulb_lantern_blue_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("terminite_bulb_lantern_blue", "terminite_bulb_lantern_blue_weight_average_color", 15));
        betterendColors.add(new Color("terminite_bulb_lantern_lime_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("terminite_bulb_lantern_lime", "terminite_bulb_lantern_lime_weight_average_color", 15));
        betterendColors.add(new Color("terminite_bulb_lantern_magenta_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("terminite_bulb_lantern_magenta", "terminite_bulb_lantern_magenta_weight_average_color", 15));
        betterendColors.add(new Color("terminite_bulb_lantern_red_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("terminite_bulb_lantern_red", "terminite_bulb_lantern_red_weight_average_color", 15));
        betterendColors.add(new Color("terminite_bulb_lantern_orange_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("terminite_bulb_lantern_orange", "terminite_bulb_lantern_orange_weight_average_color", 15));
        betterendColors.add(new Color("terminite_bulb_lantern_purple_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("terminite_bulb_lantern_purple", "terminite_bulb_lantern_purple_weight_average_color", 15));
        betterendColors.add(new Color("terminite_bulb_lantern_cyan_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("terminite_bulb_lantern_cyan", "terminite_bulb_lantern_cyan_weight_average_color", 15));
        betterendColors.add(new Color("terminite_bulb_lantern_brown_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("terminite_bulb_lantern_brown", "terminite_bulb_lantern_brown_weight_average_color", 15));
        betterendColors.add(new Color("terminite_bulb_lantern_green_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("terminite_bulb_lantern_green", "terminite_bulb_lantern_green_weight_average_color", 15));
        betterendColors.add(new Color("terminite_bulb_lantern_yellow_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("terminite_bulb_lantern_yellow", "terminite_bulb_lantern_yellow_weight_average_color", 15));
        betterendColors.add(new Color("terminite_bulb_lantern_pink_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("terminite_bulb_lantern_pink", "terminite_bulb_lantern_pink_weight_average_color", 15));
        betterendColors.add(new Color("terminite_bulb_lantern_light_blue_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("terminite_bulb_lantern_light_blue", "terminite_bulb_lantern_light_blue_weight_average_color", 15));
        betterendColors.add(new Color("aurora_crystal_weight_average_color", 209, 231, 238, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("aurora_crystal", "aurora_crystal_weight_average_color", 15));
        betterendLightSourceItems.add(new LightSource("aurora_crystal", "aurora_crystal_weight_average_color", 15));
        betterendColors.add(new Color("smaragdant_crystal_shard_weight_average_color", 0, 201, 150, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("smaragdant_crystal_shard", "smaragdant_crystal_shard_weight_average_color", 15));
        betterendLightSourceItems.add(new LightSource("smaragdant_crystal_shard", "smaragdant_crystal_shard_weight_average_color", 15));
        betterendColors.add(new Color("smaragdant_crystal_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("smaragdant_crystal", "smaragdant_crystal_weight_average_color", 15));
        betterendLightSourceItems.add(new LightSource("smaragdant_crystal", "smaragdant_crystal_weight_average_color", 15));
        betterendColors.add(new Color("smaragdant_crystal_polished_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("smaragdant_crystal_polished", "smaragdant_crystal_polished_weight_average_color", 15));
        betterendColors.add(new Color("smaragdant_crystal_tiles_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("smaragdant_crystal_tiles", "smaragdant_crystal_tiles_weight_average_color", 15));
        betterendColors.add(new Color("smaragdant_crystal_pillar_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("smaragdant_crystal_pillar", "smaragdant_crystal_pillar_weight_average_color", 15));
        betterendColors.add(new Color("smaragdant_crystal_stairs_weight_average_color", 0, 197, 149, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("smaragdant_crystal_stairs", "smaragdant_crystal_stairs_weight_average_color", 15));
        betterendLightSourceItems.add(new LightSource("smaragdant_crystal_stairs", "smaragdant_crystal_stairs_weight_average_color", 15));
        betterendColors.add(new Color("smaragdant_crystal_slab_weight_average_color", 0, 197, 149, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("smaragdant_crystal_slab", "smaragdant_crystal_slab_weight_average_color", 15));
        betterendLightSourceItems.add(new LightSource("smaragdant_crystal_slab", "smaragdant_crystal_slab_weight_average_color", 15));
        betterendColors.add(new Color("smaragdant_crystal_wall_weight_average_color", 0, 197, 149, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("smaragdant_crystal_wall", "smaragdant_crystal_wall_weight_average_color", 15));
        betterendLightSourceItems.add(new LightSource("smaragdant_crystal_wall", "smaragdant_crystal_wall_weight_average_color", 15));
        betterendColors.add(new Color("smaragdant_crystal_pedestal_weight_average_color", 0, 203, 150, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("smaragdant_crystal_pedestal", "smaragdant_crystal_pedestal_weight_average_color", 15));
        betterendLightSourceItems.add(new LightSource("smaragdant_crystal_pedestal", "smaragdant_crystal_pedestal_weight_average_color", 15));
        betterendColors.add(new Color("smaragdant_crystal_bricks_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("smaragdant_crystal_bricks", "smaragdant_crystal_bricks_weight_average_color", 15));
        betterendColors.add(new Color("smaragdant_crystal_bricks_stairs_weight_average_color", 0, 208, 152, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("smaragdant_crystal_bricks_stairs", "smaragdant_crystal_bricks_stairs_weight_average_color", 15));
        betterendLightSourceItems.add(new LightSource("smaragdant_crystal_bricks_stairs", "smaragdant_crystal_bricks_stairs_weight_average_color", 15));
        betterendColors.add(new Color("smaragdant_crystal_bricks_slab_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("smaragdant_crystal_bricks_slab", "smaragdant_crystal_bricks_slab_weight_average_color", 15));
        betterendColors.add(new Color("smaragdant_crystal_bricks_wall_weight_average_color", 0, 208, 152, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("smaragdant_crystal_bricks_wall", "smaragdant_crystal_bricks_wall_weight_average_color", 15));
        betterendLightSourceItems.add(new LightSource("smaragdant_crystal_bricks_wall", "smaragdant_crystal_bricks_wall_weight_average_color", 15));
        betterendColors.add(new Color("budding_smaragdant_crystal_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("budding_smaragdant_crystal", "budding_smaragdant_crystal_weight_average_color", 15));
        betterendLightSourceItems.add(new LightSource("budding_smaragdant_crystal", "budding_smaragdant_crystal_weight_average_color", 15));
        betterendColors.add(new Color("respawn_obelisk_weight_average_color", 233, 170, 49, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("respawn_obelisk", "respawn_obelisk_weight_average_color", 15));
        betterendLightSourceItems.add(new LightSource("respawn_obelisk", "respawn_obelisk_weight_average_color", 15));
        betterendColors.add(new Color("andesite_lantern_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("andesite_lantern", "andesite_lantern_weight_average_color", 15));
        betterendColors.add(new Color("diorite_lantern_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("diorite_lantern", "diorite_lantern_weight_average_color", 15));
        betterendColors.add(new Color("granite_lantern_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("granite_lantern", "granite_lantern_weight_average_color", 15));
        betterendColors.add(new Color("quartz_lantern_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("quartz_lantern", "quartz_lantern_weight_average_color", 15));
        betterendColors.add(new Color("purpur_lantern_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("purpur_lantern", "purpur_lantern_weight_average_color", 15));
        betterendColors.add(new Color("end_stone_lantern_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("end_stone_lantern", "end_stone_lantern_weight_average_color", 15));
        betterendColors.add(new Color("blackstone_lantern_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("blackstone_lantern", "blackstone_lantern_weight_average_color", 15));
        betterendColors.add(new Color("iron_bulb_lantern_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("iron_bulb_lantern", "iron_bulb_lantern_weight_average_color", 15));
        betterendColors.add(new Color("iron_bulb_lantern_white_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("iron_bulb_lantern_white", "iron_bulb_lantern_white_weight_average_color", 15));
        betterendColors.add(new Color("iron_bulb_lantern_gray_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("iron_bulb_lantern_gray", "iron_bulb_lantern_gray_weight_average_color", 15));
        betterendColors.add(new Color("iron_bulb_lantern_light_gray_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("iron_bulb_lantern_light_gray", "iron_bulb_lantern_light_gray_weight_average_color", 15));
        betterendColors.add(new Color("iron_bulb_lantern_black_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("iron_bulb_lantern_black", "iron_bulb_lantern_black_weight_average_color", 15));
        betterendColors.add(new Color("iron_bulb_lantern_blue_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("iron_bulb_lantern_blue", "iron_bulb_lantern_blue_weight_average_color", 15));
        betterendColors.add(new Color("iron_bulb_lantern_lime_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("iron_bulb_lantern_lime", "iron_bulb_lantern_lime_weight_average_color", 15));
        betterendColors.add(new Color("iron_bulb_lantern_magenta_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("iron_bulb_lantern_magenta", "iron_bulb_lantern_magenta_weight_average_color", 15));
        betterendColors.add(new Color("iron_bulb_lantern_red_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("iron_bulb_lantern_red", "iron_bulb_lantern_red_weight_average_color", 15));
        betterendColors.add(new Color("iron_bulb_lantern_orange_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("iron_bulb_lantern_orange", "iron_bulb_lantern_orange_weight_average_color", 15));
        betterendColors.add(new Color("iron_bulb_lantern_purple_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("iron_bulb_lantern_purple", "iron_bulb_lantern_purple_weight_average_color", 15));
        betterendColors.add(new Color("iron_bulb_lantern_cyan_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("iron_bulb_lantern_cyan", "iron_bulb_lantern_cyan_weight_average_color", 15));
        betterendColors.add(new Color("iron_bulb_lantern_brown_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("iron_bulb_lantern_brown", "iron_bulb_lantern_brown_weight_average_color", 15));
        betterendColors.add(new Color("iron_bulb_lantern_green_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("iron_bulb_lantern_green", "iron_bulb_lantern_green_weight_average_color", 15));
        betterendColors.add(new Color("iron_bulb_lantern_yellow_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("iron_bulb_lantern_yellow", "iron_bulb_lantern_yellow_weight_average_color", 15));
        betterendColors.add(new Color("iron_bulb_lantern_pink_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("iron_bulb_lantern_pink", "iron_bulb_lantern_pink_weight_average_color", 15));
        betterendColors.add(new Color("iron_bulb_lantern_light_blue_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("iron_bulb_lantern_light_blue", "iron_bulb_lantern_light_blue_weight_average_color", 15));
        betterendColors.add(new Color("iron_chandelier_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("iron_chandelier", "iron_chandelier_weight_average_color", 15));
        betterendColors.add(new Color("gold_chandelier_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("gold_chandelier", "gold_chandelier_weight_average_color", 15));
        betterendColors.add(new Color("end_stone_furnace_weight_average_color", 0, 0, 0, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("end_stone_furnace", "end_stone_furnace_weight_average_color", 13, "lit=true"));
        betterendColors.add(new Color("end_stone_smelter_weight_average_color", 182, 164, 120, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("end_stone_smelter", "end_stone_smelter_weight_average_color", 15, "lit=true"));
        betterendLightSourceItems.add(new LightSource("end_stone_smelter", "end_stone_smelter_weight_average_color", 15));
        betterendColors.add(new Color("end_portal_block_weight_average_color", 92, 62, 235, Config.auto_alpha));
        betterendLightSourceBlocks.add(new LightSource("end_portal_block", "end_portal_block_weight_average_color", 15));
        betterendLightSourceItems.add(new LightSource("end_portal_block", "end_portal_block_weight_average_color", 15));
        supportedMods.add(new SupportedMod("betterend", "betterend", "better-end", betterendColors, betterendLightSourceBlocks, betterendLightSourceItems));

        // Mod ID: another_furniture
        ArrayList<Color> another_furnitureColors = new ArrayList<>();
        ArrayList<LightSource> another_furnitureLightSourceBlocks = new ArrayList<>();
        ArrayList<LightSource> another_furnitureLightSourceItems = new ArrayList<>();

        another_furnitureColors.add(new Color("white_lamp_weight_average_color", 231, 233, 231, Config.auto_alpha));
        another_furnitureLightSourceBlocks.add(new LightSource("white_lamp", "white_lamp_weight_average_color", 5, "lit=true,level=1"));
        another_furnitureLightSourceItems.add(new LightSource("white_lamp", "white_lamp_weight_average_color", 5));
        another_furnitureLightSourceBlocks.add(new LightSource("white_lamp", "white_lamp_weight_average_color", 10, "lit=true,level=2"));
        another_furnitureLightSourceBlocks.add(new LightSource("white_lamp", "white_lamp_weight_average_color", 15, "lit=true,level=3"));
        another_furnitureColors.add(new Color("orange_lamp_weight_average_color", 246, 127, 23, Config.auto_alpha));
        another_furnitureLightSourceBlocks.add(new LightSource("orange_lamp", "orange_lamp_weight_average_color", 5, "lit=true,level=1"));
        another_furnitureLightSourceItems.add(new LightSource("orange_lamp", "orange_lamp_weight_average_color", 5));
        another_furnitureLightSourceBlocks.add(new LightSource("orange_lamp", "orange_lamp_weight_average_color", 10, "lit=true,level=2"));
        another_furnitureLightSourceBlocks.add(new LightSource("orange_lamp", "orange_lamp_weight_average_color", 15, "lit=true,level=3"));
        another_furnitureColors.add(new Color("magenta_lamp_weight_average_color", 184, 61, 170, Config.auto_alpha));
        another_furnitureLightSourceBlocks.add(new LightSource("magenta_lamp", "magenta_lamp_weight_average_color", 5, "lit=true,level=1"));
        another_furnitureLightSourceItems.add(new LightSource("magenta_lamp", "magenta_lamp_weight_average_color", 5));
        another_furnitureLightSourceBlocks.add(new LightSource("magenta_lamp", "magenta_lamp_weight_average_color", 10, "lit=true,level=2"));
        another_furnitureLightSourceBlocks.add(new LightSource("magenta_lamp", "magenta_lamp_weight_average_color", 15, "lit=true,level=3"));
        another_furnitureColors.add(new Color("light_blue_lamp_weight_average_color", 44, 157, 210, Config.auto_alpha));
        another_furnitureLightSourceBlocks.add(new LightSource("light_blue_lamp", "light_blue_lamp_weight_average_color", 5, "lit=true,level=1"));
        another_furnitureLightSourceItems.add(new LightSource("light_blue_lamp", "light_blue_lamp_weight_average_color", 5));
        another_furnitureLightSourceBlocks.add(new LightSource("light_blue_lamp", "light_blue_lamp_weight_average_color", 10, "lit=true,level=2"));
        another_furnitureLightSourceBlocks.add(new LightSource("light_blue_lamp", "light_blue_lamp_weight_average_color", 15, "lit=true,level=3"));
        another_furnitureColors.add(new Color("yellow_lamp_weight_average_color", 251, 199, 37, Config.auto_alpha));
        another_furnitureLightSourceBlocks.add(new LightSource("yellow_lamp", "yellow_lamp_weight_average_color", 5, "lit=true,level=1"));
        another_furnitureLightSourceItems.add(new LightSource("yellow_lamp", "yellow_lamp_weight_average_color", 5));
        another_furnitureLightSourceBlocks.add(new LightSource("yellow_lamp", "yellow_lamp_weight_average_color", 10, "lit=true,level=2"));
        another_furnitureLightSourceBlocks.add(new LightSource("yellow_lamp", "yellow_lamp_weight_average_color", 15, "lit=true,level=3"));
        another_furnitureColors.add(new Color("lime_lamp_weight_average_color", 123, 192, 31, Config.auto_alpha));
        another_furnitureLightSourceBlocks.add(new LightSource("lime_lamp", "lime_lamp_weight_average_color", 5, "lit=true,level=1"));
        another_furnitureLightSourceItems.add(new LightSource("lime_lamp", "lime_lamp_weight_average_color", 5));
        another_furnitureLightSourceBlocks.add(new LightSource("lime_lamp", "lime_lamp_weight_average_color", 10, "lit=true,level=2"));
        another_furnitureLightSourceBlocks.add(new LightSource("lime_lamp", "lime_lamp_weight_average_color", 15, "lit=true,level=3"));
        another_furnitureColors.add(new Color("pink_lamp_weight_average_color", 237, 130, 163, Config.auto_alpha));
        another_furnitureLightSourceBlocks.add(new LightSource("pink_lamp", "pink_lamp_weight_average_color", 5, "lit=true,level=1"));
        another_furnitureLightSourceItems.add(new LightSource("pink_lamp", "pink_lamp_weight_average_color", 5));
        another_furnitureLightSourceBlocks.add(new LightSource("pink_lamp", "pink_lamp_weight_average_color", 10, "lit=true,level=2"));
        another_furnitureLightSourceBlocks.add(new LightSource("pink_lamp", "pink_lamp_weight_average_color", 15, "lit=true,level=3"));
        another_furnitureColors.add(new Color("gray_lamp_weight_average_color", 114, 113, 100, Config.auto_alpha));
        another_furnitureLightSourceBlocks.add(new LightSource("gray_lamp", "gray_lamp_weight_average_color", 5, "lit=true,level=1"));
        another_furnitureLightSourceItems.add(new LightSource("gray_lamp", "gray_lamp_weight_average_color", 5));
        another_furnitureLightSourceBlocks.add(new LightSource("gray_lamp", "gray_lamp_weight_average_color", 10, "lit=true,level=2"));
        another_furnitureLightSourceBlocks.add(new LightSource("gray_lamp", "gray_lamp_weight_average_color", 15, "lit=true,level=3"));
        another_furnitureColors.add(new Color("light_gray_lamp_weight_average_color", 148, 143, 128, Config.auto_alpha));
        another_furnitureLightSourceBlocks.add(new LightSource("light_gray_lamp", "light_gray_lamp_weight_average_color", 5, "lit=true,level=1"));
        another_furnitureLightSourceItems.add(new LightSource("light_gray_lamp", "light_gray_lamp_weight_average_color", 5));
        another_furnitureLightSourceBlocks.add(new LightSource("light_gray_lamp", "light_gray_lamp_weight_average_color", 10, "lit=true,level=2"));
        another_furnitureLightSourceBlocks.add(new LightSource("light_gray_lamp", "light_gray_lamp_weight_average_color", 15, "lit=true,level=3"));
        another_furnitureColors.add(new Color("cyan_lamp_weight_average_color", 27, 155, 151, Config.auto_alpha));
        another_furnitureLightSourceBlocks.add(new LightSource("cyan_lamp", "cyan_lamp_weight_average_color", 5, "lit=true,level=1"));
        another_furnitureLightSourceItems.add(new LightSource("cyan_lamp", "cyan_lamp_weight_average_color", 5));
        another_furnitureLightSourceBlocks.add(new LightSource("cyan_lamp", "cyan_lamp_weight_average_color", 10, "lit=true,level=2"));
        another_furnitureLightSourceBlocks.add(new LightSource("cyan_lamp", "cyan_lamp_weight_average_color", 15, "lit=true,level=3"));
        another_furnitureColors.add(new Color("purple_lamp_weight_average_color", 128, 46, 173, Config.auto_alpha));
        another_furnitureLightSourceBlocks.add(new LightSource("purple_lamp", "purple_lamp_weight_average_color", 5, "lit=true,level=1"));
        another_furnitureLightSourceItems.add(new LightSource("purple_lamp", "purple_lamp_weight_average_color", 5));
        another_furnitureLightSourceBlocks.add(new LightSource("purple_lamp", "purple_lamp_weight_average_color", 10, "lit=true,level=2"));
        another_furnitureLightSourceBlocks.add(new LightSource("purple_lamp", "purple_lamp_weight_average_color", 15, "lit=true,level=3"));
        another_furnitureColors.add(new Color("blue_lamp_weight_average_color", 68, 95, 179, Config.auto_alpha));
        another_furnitureLightSourceBlocks.add(new LightSource("blue_lamp", "blue_lamp_weight_average_color", 5, "lit=true,level=1"));
        another_furnitureLightSourceItems.add(new LightSource("blue_lamp", "blue_lamp_weight_average_color", 5));
        another_furnitureLightSourceBlocks.add(new LightSource("blue_lamp", "blue_lamp_weight_average_color", 10, "lit=true,level=2"));
        another_furnitureLightSourceBlocks.add(new LightSource("blue_lamp", "blue_lamp_weight_average_color", 15, "lit=true,level=3"));
        another_furnitureColors.add(new Color("brown_lamp_weight_average_color", 143, 94, 55, Config.auto_alpha));
        another_furnitureLightSourceBlocks.add(new LightSource("brown_lamp", "brown_lamp_weight_average_color", 5, "lit=true,level=1"));
        another_furnitureLightSourceItems.add(new LightSource("brown_lamp", "brown_lamp_weight_average_color", 5));
        another_furnitureLightSourceBlocks.add(new LightSource("brown_lamp", "brown_lamp_weight_average_color", 10, "lit=true,level=2"));
        another_furnitureLightSourceBlocks.add(new LightSource("brown_lamp", "brown_lamp_weight_average_color", 15, "lit=true,level=3"));
        another_furnitureColors.add(new Color("green_lamp_weight_average_color", 103, 125, 30, Config.auto_alpha));
        another_furnitureLightSourceBlocks.add(new LightSource("green_lamp", "green_lamp_weight_average_color", 5, "lit=true,level=1"));
        another_furnitureLightSourceItems.add(new LightSource("green_lamp", "green_lamp_weight_average_color", 5));
        another_furnitureLightSourceBlocks.add(new LightSource("green_lamp", "green_lamp_weight_average_color", 10, "lit=true,level=2"));
        another_furnitureLightSourceBlocks.add(new LightSource("green_lamp", "green_lamp_weight_average_color", 15, "lit=true,level=3"));
        another_furnitureColors.add(new Color("red_lamp_weight_average_color", 175, 53, 44, Config.auto_alpha));
        another_furnitureLightSourceBlocks.add(new LightSource("red_lamp", "red_lamp_weight_average_color", 5, "lit=true,level=1"));
        another_furnitureLightSourceItems.add(new LightSource("red_lamp", "red_lamp_weight_average_color", 5));
        another_furnitureLightSourceBlocks.add(new LightSource("red_lamp", "red_lamp_weight_average_color", 10, "lit=true,level=2"));
        another_furnitureLightSourceBlocks.add(new LightSource("red_lamp", "red_lamp_weight_average_color", 15, "lit=true,level=3"));
        another_furnitureColors.add(new Color("black_lamp_weight_average_color", 148, 118, 68, Config.auto_alpha));
        another_furnitureLightSourceBlocks.add(new LightSource("black_lamp", "black_lamp_weight_average_color", 5, "lit=true,level=1"));
        another_furnitureLightSourceItems.add(new LightSource("black_lamp", "black_lamp_weight_average_color", 5));
        another_furnitureLightSourceBlocks.add(new LightSource("black_lamp", "black_lamp_weight_average_color", 10, "lit=true,level=2"));
        another_furnitureLightSourceBlocks.add(new LightSource("black_lamp", "black_lamp_weight_average_color", 15, "lit=true,level=3"));
        supportedMods.add(new SupportedMod("another_furniture", "another_furniture", "another_furniture", another_furnitureColors, another_furnitureLightSourceBlocks, another_furnitureLightSourceItems));

        return supportedMods;
    }
}
